language: ruby
bundler_args: --without debugger
rvm:
  - 1.8.7
  - 1.9.3
  - 2.1.2
  - ruby-head
matrix:
  allow_failures:
    - 2.1.2
    - rvm: ruby-head

script:
  - bundle exec rake test
notifications:
  email:
    recipients:
      - ngiger@ywesee.com
